apiVersion: apps/v1
kind: Deployment
metadata:
  name: avoxi-test-mjl
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: avoxi-test-mjl
  template:
    containers:
      - command:
          - /main
        image: docker.io/bigfatmiddle/avoxi-test:3c41b60d7c83b84a3f77a70b97a92f3f40e5828b
        imagePullPolicy: IfNotPresent
        name: avoxi-test
        ports:
          - containerPort: 8081
            protocol: TCP
          - containerPort: 8082
            name: http
            protocol: TCP
status: {}
